menus:
  - title: Blog
    index: /
  - title: Timeline
    index: /timeline
  - title: Music
    index: /music
  - title: RSS
    index: /rss.xml
  - title: About
    index: /about
  - title: Donate
    index: /blog/donation
  - title: 购买贴纸
    index: http://stickeroverflow.xyz

skills:
  - Fundamental HTML/CSS/ECMAScript(5/6/7)
  - React
  - Vue.js
  - HTTP Protocol
  - Git
  - ReasonML
  - TypeScript

talks:
  - title: Vue and Native
    date: 2016-05-01
    at: 珠三角技术沙龙
  - title: TypeScript
    date: 2016-12-05
    at: Node 地下铁
    slide: https://slides.com/randylu/deck-3

contacts:
  - className: twitter
    href: https://twitter.com/randyloop
    title: '@randyloop'
  - className: weibo
    href: http://weibo.com/djyde
    title: '@米斯特软的'
  - className: zhihu
    href: https://zhihu.com/people/djyde
    title: 卢涛南
  - className: github
    href: https://github.com/djyde
    title: djyde
  - className: medium
    href: https://medium.com/@djyde
    title: '@djyde'
  - className: email
    href: mailto:randypriv@gmail.com
    title: randypriv at gmail
  - className: instagram
    href: https://www.instagram.com/randy_fam/
    title: 'randy_fam'
  - className: telegram
    href: https://t.me/djyde
    title: '@djyde'

ga_track_id: UA-72147868-2
